import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, CheckCircle2, ExternalLink, Mail, MapPin, Phone, Stethoscope } from "lucide-react";
import doctorAsset from "@/assets/dr-prashanth-kumar.png.asset.json";
import xrayImage from "@/assets/orthopedic-xray.jpg";
import rehabImage from "@/assets/rehabilitation-care.jpg";
import deskImage from "@/assets/joint-care-desk.jpg";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/section-heading";
import { ConsultationForm } from "@/components/consultation-form";
import { articles, expertise, locations, services } from "@/lib/site-data";

export const images = { doctor: doctorAsset.url, xray: xrayImage, rehab: rehabImage, desk: deskImage };

export function Hero() {
  return <section className="relative overflow-hidden bg-hero"><div className="site-container grid min-h-[760px] items-center gap-10 pb-10 pt-14 lg:grid-cols-[1.04fr_.96fr] lg:pb-0 lg:pt-8">
    <div className="relative z-10 py-6"><p className="eyebrow text-accent">Orthopedic & Joint Replacement Specialist</p><h1 className="mt-5 max-w-3xl text-4xl font-bold leading-[1.1] text-foreground sm:text-5xl lg:text-6xl xl:text-7xl">Expert Orthopedic Care for Better Movement and Better Living</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Dr. K. Prashanth Kumar is an experienced Orthopedic & Joint Replacement Surgeon providing comprehensive care for joint problems, fractures, sports injuries, arthritis and trauma.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="min-h-12"><Link to="/contact" hash="consultation"><CalendarDays/>Book a Consultation</Link></Button><Button asChild variant="outline" size="lg" className="min-h-12 bg-background/70"><Link to="/services">Explore Services<ArrowRight/></Link></Button></div><div className="mt-10 grid grid-cols-2 gap-x-5 gap-y-4 border-t border-border pt-6 sm:grid-cols-4">{["10+ Years Experience", "Orthopedic Specialist", "Joint Replacement", "Patient-Centered Care"].map((item) => <p key={item} className="flex items-start gap-2 text-xs font-bold leading-5 text-foreground"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-accent"/>{item}</p>)}</div></div>
    <div className="relative self-end"><div className="absolute bottom-14 left-0 z-10 rounded-md bg-background p-5 shadow-premium sm:left-3"><strong className="block text-3xl text-primary">10+ Years</strong><span className="text-sm text-muted-foreground">of orthopedic experience</span></div><div className="mx-auto max-w-[590px] overflow-hidden rounded-t-[48%] border-x border-t border-border bg-secondary"><img src={doctorAsset.url} width="768" height="768" alt="Dr. K. Prashanth Kumar, Orthopedic and Joint Replacement Surgeon" className="aspect-[4/5] w-full object-cover object-top" fetchPriority="high"/></div></div>
  </div></section>;
}

export function TrustBar() { return <section className="border-y border-border bg-background"><div className="site-container grid divide-y divide-border sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{[["10+", "Years of Experience"], ["Orthopedic", "Specialist"], ["Joint Replacement", "Expertise"], ["Comprehensive", "Patient Care"]].map(([value, label]) => <div key={label} className="px-5 py-7 text-center"><strong className="block text-xl font-bold text-primary">{value}</strong><span className="mt-1 block text-sm text-muted-foreground">{label}</span></div>)}</div></section>; }

export function AboutSection({ compact = false }: { compact?: boolean }) {
  return <section className="section-space bg-background"><div className="site-container grid items-center gap-12 lg:grid-cols-[.88fr_1.12fr]">
    <div className="relative"><div className="overflow-hidden rounded-lg bg-secondary"><img src={doctorAsset.url} loading="lazy" width="768" height="768" alt="Portrait of Dr. K. Prashanth Kumar" className="aspect-[4/5] w-full object-cover object-top"/></div><div className="absolute -bottom-5 right-4 rounded-md bg-primary p-5 text-primary-foreground shadow-premium sm:right-[-24px]"><p className="text-xs font-bold uppercase text-accent-soft">Qualifications</p><strong className="mt-1 block">MBBS, D.Ortho, DNB Ortho</strong></div></div>
    <div><SectionHeading eyebrow="About the Doctor" title="Meet Dr. K. Prashanth Kumar" text="Experienced Orthopedic Care with a Patient-First Approach"/><p className="mt-7 leading-7 text-muted-foreground">Dr. K. Prashanth Kumar provides orthopedic care across joint replacement, trauma and fracture care, sports injuries, arthritis and rheumatology. His approach begins with understanding each patient's concerns, evaluating the condition carefully and planning treatment around individual needs.</p>{!compact ? <p className="mt-4 leading-7 text-muted-foreground">Where suitable, conservative treatment is considered alongside procedural and surgical options, with clear communication supporting each stage of care and recovery.</p> : null}<div className="mt-8 grid gap-3 sm:grid-cols-3">{[["Qualification", "MBBS, D.Ortho, DNB Ortho"], ["Experience", "10+ Years"], ["Specialty", "Orthopedics & Joint Replacement"]].map(([label, value]) => <div className="rounded-md border border-border bg-muted p-4" key={label}><span className="text-xs font-bold uppercase text-accent">{label}</span><strong className="mt-2 block text-sm">{value}</strong></div>)}</div><Button asChild variant="outline" size="lg" className="mt-8"><Link to="/about">Learn More About the Doctor<ArrowRight/></Link></Button></div>
  </div></section>;
}

export function ExpertiseSection() { return <section className="section-space bg-muted"><div className="site-container"><SectionHeading eyebrow="Clinical Focus" title="Areas of Expertise" text="Specialized care for a wide range of orthopedic and joint conditions."/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{expertise.map(({ title, text, icon: Icon }) => <article key={title} className="group rounded-md border border-border bg-background p-6 transition hover:-translate-y-1 hover:border-accent/40 hover:shadow-premium"><span className="grid size-11 place-items-center rounded-md bg-accent-soft text-accent"><Icon className="size-5"/></span><h3 className="mt-6 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><Link to="/expertise" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Learn More<ArrowRight className="size-4 transition group-hover:translate-x-1"/></Link></article>)}</div></div></section>; }

export function ServicesSection() { return <section className="section-space bg-background"><div className="site-container"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><SectionHeading eyebrow="Orthopedic Services" title="Comprehensive Orthopedic Services" text="From diagnosis to treatment and recovery, providing personalized orthopedic care."/><Button asChild variant="outline"><Link to="/services">View all services<ArrowRight/></Link></Button></div><div className="mt-10 grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-3">{services.map(([number, title, text]) => <article key={number} className="group border-b border-r border-border p-7 transition hover:bg-muted"><div className="flex items-center justify-between"><span className="text-sm font-bold text-accent">{number}</span><Stethoscope className="size-5 text-muted-foreground"/></div><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-3 min-h-18 text-sm leading-6 text-muted-foreground">{text}</p><Link to="/services" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Learn More<ArrowRight className="size-4"/></Link></article>)}</div></div></section>; }

export function RheumatologySection() { return <section className="section-space bg-primary text-primary-foreground"><div className="site-container"><SectionHeading light eyebrow="Additional Expertise" title="Rheumatology & Arthritis Care" text="Comprehensive support for joint pain, arthritis and related conditions."/><div className="mt-10 grid gap-px overflow-hidden rounded-md bg-primary-foreground/15 md:grid-cols-2 lg:grid-cols-4">{[["Arthritis Management", "Personalized evaluation and management of arthritis-related symptoms."], ["Autoimmune Joint Disorders", "Care focused on joint conditions associated with autoimmune disorders."], ["Chronic Pain Control", "Structured approaches to managing persistent musculoskeletal and joint pain."], ["Physical Therapy Guidance", "Guidance supporting mobility, recovery and functional improvement."]].map(([title, text]) => <article className="bg-primary p-6" key={title}><HeartIcon/><h3 className="mt-6 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/70">{text}</p></article>)}</div><Button asChild className="mt-8 bg-accent text-accent-foreground hover:bg-accent/90"><Link to="/contact" hash="consultation">Discuss Your Condition<ArrowRight/></Link></Button></div></section>; }

function HeartIcon(){return <span className="grid size-10 place-items-center rounded-md border border-primary-foreground/20 text-accent-soft"><CheckCircle2 className="size-5"/></span>}

export function CareProcess() { return <section className="section-space bg-muted"><div className="site-container"><SectionHeading eyebrow="Your Care Journey" title="A Clear Path to Better Care"/><ol className="mt-12 grid gap-8 lg:grid-cols-4">{[["01", "Consultation", "Understand symptoms, concerns and medical history."], ["02", "Evaluation", "Clinical assessment and appropriate diagnostic evaluation."], ["03", "Treatment Plan", "Develop a personalized treatment approach."], ["04", "Recovery & Follow-Up", "Support recovery and ongoing care."]].map(([num,title,text], index) => <li key={num} className="relative border-l-2 border-accent pl-6 lg:border-l-0 lg:border-t-2 lg:pl-0 lg:pt-7"><span className="absolute -left-3 top-0 grid size-6 place-items-center rounded-full bg-accent text-[10px] font-bold text-accent-foreground lg:-top-3 lg:left-0">{index + 1}</span><span className="text-xs font-bold text-accent">STEP {num}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></li>)}</ol></div></section>; }

export function GallerySection() { return <section className="section-space bg-background"><div className="site-container"><SectionHeading eyebrow="Clinical Care" title="Success Stories & Surgical Care" text="A privacy-conscious visual glimpse into orthopedic assessment, treatment and recovery support."/><div className="mt-10 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><figure className="group relative overflow-hidden rounded-md"><img src={xrayImage} loading="lazy" width="1400" height="900" alt="Clinical review of a knee X-ray" className="aspect-[16/10] size-full object-cover transition duration-500 group-hover:scale-[1.02]"/><figcaption className="absolute inset-x-0 bottom-0 bg-primary/90 p-4 text-sm font-semibold text-primary-foreground">Clinical evaluation and imaging review</figcaption></figure><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><figure className="group relative overflow-hidden rounded-md"><img src={rehabImage} loading="lazy" width="1400" height="900" alt="Guided orthopedic rehabilitation session" className="aspect-[16/10] size-full object-cover transition duration-500 group-hover:scale-[1.02]"/><figcaption className="absolute inset-x-0 bottom-0 bg-primary/90 p-3 text-sm text-primary-foreground">Mobility and recovery guidance</figcaption></figure><figure className="group relative overflow-hidden rounded-md"><img src={deskImage} loading="lazy" width="1400" height="900" alt="Knee model in an orthopedic consultation setting" className="aspect-[16/10] size-full object-cover transition duration-500 group-hover:scale-[1.02]"/><figcaption className="absolute inset-x-0 bottom-0 bg-primary/90 p-3 text-sm text-primary-foreground">Clear, informed treatment discussions</figcaption></figure></div></div><p className="mt-4 text-xs text-muted-foreground">Images are illustrative and do not depict named patients, individual outcomes or before-and-after results.</p></div></section>; }

export function HealthTipsSection({ limit }: { limit?: number }) { const items = limit ? articles.slice(0, limit) : articles; return <section className="section-space bg-muted"><div className="site-container"><SectionHeading eyebrow="Patient Education" title="Health Tips & Patient Education" text="Simple information to help patients understand orthopedic health and recovery."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((article, index) => <article key={article.slug} className="overflow-hidden rounded-md border border-border bg-background"><img src={[deskImage, xrayImage, rehabImage][index % 3]} loading="lazy" width="1400" height="900" alt="" className="aspect-[16/9] w-full object-cover"/><div className="p-6"><span className="text-xs font-bold uppercase text-accent">{article.category}</span><h3 className="mt-2 text-xl font-bold">{article.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{article.summary}</p><Link to="/health-tips/$slug" params={{ slug: article.slug }} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Read More<ArrowRight className="size-4"/></Link></div></article>)}</div>{limit ? <Button asChild variant="outline" className="mt-8"><Link to="/health-tips">View all health tips<ArrowRight/></Link></Button> : null}</div></section>; }

export function WhyChoose() { return <section className="section-space bg-background"><div className="site-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Thoughtful Care" title="Why Patients Choose Dr. Prashanth Kumar"/><div className="grid gap-4 sm:grid-cols-2">{[["Experienced Care", "10+ years of orthopedic experience."], ["Comprehensive Expertise", "Orthopedic, trauma, joint replacement and arthritis care."], ["Personalized Treatment", "Treatment approaches tailored to individual patient needs."], ["Patient-Centered Approach", "Clear communication and focus on patient concerns."]].map(([title,text]) => <article key={title} className="border-t-2 border-accent pt-5"><h3 className="text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>; }

export function LocationsSection() { return <section className="section-space bg-muted"><div className="site-container"><SectionHeading eyebrow="Visit the Doctor" title="Consultation Locations" text="Find the clinic location convenient for your consultation."/><div className="mt-10 grid gap-5 lg:grid-cols-2">{locations.map((location, index) => <article key={location.name} className="rounded-md border border-border bg-background p-7"><div className="flex items-start justify-between gap-4"><span className="text-xs font-bold text-accent">LOCATION 0{index + 1}</span><span className="rounded-full bg-accent-soft px-3 py-1 text-xs font-bold text-accent">{location.label}</span></div><MapPin className="mt-8 size-7 text-primary"/><h3 className="mt-4 text-2xl font-bold">{location.name}</h3><p className="mt-2 text-muted-foreground">{location.city}</p><a href={location.map} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-input px-5 text-sm font-bold text-foreground transition hover:bg-accent-soft">Get Directions<ExternalLink className="size-4"/></a></article>)}</div></div></section>; }

export function AppointmentSection() { return <section id="consultation" className="section-space scroll-mt-24 bg-background"><div className="site-container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading eyebrow="Request a Consultation" title="Ready to Take the Next Step?" text="Request a consultation or callback to discuss your orthopedic concerns."/><div className="mt-8 rounded-md bg-primary p-6 text-primary-foreground"><p className="text-sm leading-6 text-primary-foreground/75">For urgent or emergency medical concerns, contact local emergency services. This form is for non-emergency consultation requests.</p></div></div><ConsultationForm/></div></section>; }

export function ContactCards() { return <section className="section-space bg-muted"><div className="site-container"><SectionHeading eyebrow="Contact" title="Get in Touch"/><div className="mt-10 grid gap-4 md:grid-cols-3">{[{icon:Phone,title:"Call",text:"+91 90000 06684",href:"tel:+919000006684"},{icon:Mail,title:"Email",text:"drprashanthkumarkokkula@gmail.com",href:"mailto:drprashanthkumarkokkula@gmail.com"},{icon:MapPin,title:"Visit Clinic",text:"Nirmal and Khanapur, Telangana",href:"/locations"}].map(({icon:Icon,title,text,href}) => <a key={title} href={href} className="min-w-0 rounded-md border border-border bg-background p-6 transition hover:border-accent/50 hover:shadow-premium"><Icon className="size-6 text-accent"/><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 break-words text-sm text-muted-foreground">{text}</p></a>)}</div></div></section>; }

export function FinalCTA() { return <section className="relative overflow-hidden bg-primary"><img src={rehabImage} loading="lazy" width="1400" height="900" alt="" className="absolute inset-0 size-full object-cover opacity-20"/><div className="absolute inset-0 bg-primary/80"/><div className="site-container relative py-20 text-center text-primary-foreground"><h2 className="text-4xl font-bold sm:text-5xl">Your Mobility Matters</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/75">Get professional orthopedic care focused on helping you move with confidence.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild className="bg-accent text-accent-foreground hover:bg-accent/90"><Link to="/contact" hash="consultation"><CalendarDays/>Book a Consultation</Link></Button><Button asChild variant="outline" className="border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><a href="tel:+919000006684"><Phone/>Call +91 90000 06684</a></Button></div></div></section>; }